### PR TITLE
checkpoint: dynamic module graphs

### PR DESCRIPTION
**Pull request by bennn**
Not finished, but here's a preview:
(The 0's are why I'm calling it "not finished")

```
> raco gtp-trace synth
ModuleGraph for synth:
======================

Requires for: array-broadcast.rkt
  - array-struct.rkt : 436
  - array-utils.rkt : 0
  - data.rkt : 0

Requires for: array-struct.rkt
  - array-utils.rkt : 18342
  - data.rkt : 2512

Requires for: array-transform.rkt
  - array-broadcast.rkt : 448
  - array-struct.rkt : 1344
  - data.rkt : 0
  - array-utils.rkt : 880

Requires for: drum.rkt
  - array-transform.rkt : 12
  - array-struct.rkt : 54
  - array-utils.rkt : 2
  - synth.rkt : 7
  - data.rkt : 0

Requires for: main.rkt
  - drum.rkt : 4
  - synth.rkt : 9
  - sequencer.rkt : 84
  - mixer.rkt : 2

Requires for: mixer.rkt
  - array-broadcast.rkt : 8
  - array-struct.rkt : 30

Requires for: sequencer.rkt
  - array-transform.rkt : 4
  - mixer.rkt : 0
  - array-struct.rkt : 320
  - synth.rkt : 4

Requires for: synth.rkt
  - array-struct.rkt : 6
  - array-utils.rkt : 445631
```

### CODE REVIEW

**Comment by bennn** [comment]
How it works:
- Build a static module graph (with all identifiers provided from each modules)
- Make a copy of the untyped program
- For each boundary, make a new "indirections" file that re-provides each identifier as a macro that expands `use-site` to a `(begin (print) use-site)`
- String-replace old requires with the "indirections" files. Instead of`(require "b.rkt")` inside `a.rkt`, you'd `(require "a-b.rkt")` inside `a.rkt`
- Run the program, count the print statements!

Not sure what's causing the 0 entries, and running `morsecode` generates NO output so maybe something's wrong with my use of [`process`](https://github.com/nuprl/gradual-typing-performance/pull/122/files#diff-397628eb3e044564ecd3b5d99fb7e43fR222)

**Comment by rfindler** [comment]
It seems to me that a bug in this code could have disastrous effects on gradual typing as a research area. So perhaps instead of just running it on the benchmark, you should make up some synthetic programs that have precise expected results and then develop a test suite that checks the output against the expectation. 

Also, you may wish to provide the output in a data-structure form (maybe you're already doing this?) so that we can write tiny scripts inside scribble papers to report on things like "X programs have property Y" where "X" is actually computed with a little loop on that data structure.

**Comment by bennn** [comment]
Added test cases for existing benchmarks (on smaller inputs). Should make a few more hypothetical program.

(The bug from last week was badly managing a subprocess. I was just pulling from its output port without checking for a clean exit.)

**Comment by bennn** [comment]
The important file is [trace.rkt](https://github.com/bennn/gradual-typing-performance/blob/utrace/tools/summarize/trace.rkt)

**Comment by bennn** [comment]
Added a few tests, it's clear that this code only tracks statically-apparent identifiers. i.e. this example would say we used a value from module `helper` just once

```
#lang racket/base

(module helper racket/base
  (provide x) (define x 4))

(require 'helper)
(define y x)
(+ y y y y y)
```

So I put a disclaimer at the top of the printouts, but otherwise seems to be working well.

**Comment by bennn** [comment]
merg'd

**Pull request closed without merging**
